on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
<<<<<<< HEAD



=======
      - uses: lukka/get-cmake@latest
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        shell: bash
        run: mkdir build && cd build && cmake ..
>>>>>>> 7501769 (fix: windows ci)

