on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install package
        run: sudo apt-get -y install qtbase5-dev libfmt-dev libyaml-cpp-dev lcov
      - name: Build and test
        run: travis/buildtestcoverage.sh
