on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - uses: lukka/get-cmake@latest
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install jinja2
        shell: bash
        run: python -m pip install jinja2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTING=OFF ..
      - name: Build
        run: msbuild build\dxfplotter.sln /property:Configuration=Release
      - name: Deploy Qt
        shell: bash
        run: |
          mkdir install
          cp build/Release/dxfplotter.exe install/dxfplotter.exe
          windeployqt install/dxfplotter.exe
      - name: Zip install files
        shell: bash
        run: |
          choco install -y zip
          zip -r dxfplotter.zip install/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dxfplotter.zip"

